permissions:
  contents: read
  pull-requests: write

on: pull_request

jobs:
  ai-pr-update:
    runs-on: ubuntu-latest
    name: AI Pull Request Update
    steps:
      - name: Check out code
        uses: actions/checkout@v2 # This step checks out the code from the repository

      - name: Summarize PR and Update Description
        id: summarize
        uses: asieke/ai-code-review@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          action: 'update-change-log'
