on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    if: "!contains(github.event.head_commit.message, 'Update changelog with recent changes')"
    steps:
      - name: Check out code
        uses: actions/checkout@v2 # This step checks out the code from the repository

      - name: Summarize the PR
        id: summarize
        uses: asieke/ai-code-review@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          who-to-greet: 'Alex Sieke'
          action: 'update-change-log'

      # Use the output from the `hello` step
      - name: Add to Changelog
        run: |
          echo "${{ steps.summarize.outputs.changelog }}" >> changelog.md

      - name: Upload Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: changelog.md
