on: pull_request

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Summarize the PR
        id: summarize
        uses: asieke/ai-code-review@v1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          who-to-greet: 'Alex Sieke'
          action: 'update-change-log'

      # Use the output from the `hello` step
      - name: Add to Changelog
        id: changelog
        run: echo "The change is ${{ steps.summarize.outputs.changelog }}"
    
